#!/usr/bin/env bash
#this is 11-manage-my-process file
MANAGE_MY_PROCESS_PID_FILE="/var/run/my_process.pid"
MANAGE_MY_PROCESS_SCRIPT="/path/to/manage_my_process"

start() {
    if [ ! -f $MANAGE_MY_PROCESS_PID_FILE ]; then
        $MANAGE_MY_PROCESS_SCRIPT &
        echo "manage_my_process started"
    else
        echo "manage_my_process is already running"
    fi
}

stop() {
    if [ -f $MANAGE_MY_PROCESS_PID_FILE ]; then
        PID=$(cat $MANAGE_MY_PROCESS_PID_FILE)
        kill $PID
        rm -f $MANAGE_MY_PROCESS_PID_FILE
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
